sudo: false
language: generic
osx_image: xcode10.2
dist: trusty
os:
- linux
- osx
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi
install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swiftenv install $(cat .swift-version) | grep -qe "\(been\|already\) installed"; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait swift test; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make test_darwin; fi

after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash <(curl -s https://codecov.io/bash); fi
